//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class creditos
    {
        public int id_credito { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public System.DateTime vencimiento { get; set; }
        public bool cancelado { get; set; }
        public string fk_cliente { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
