//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura_productos
    {
        public int id { get; set; }
        public Nullable<int> fk_factura { get; set; }
        public Nullable<int> fk_producto { get; set; }
    
        public virtual facturas facturas { get; set; }
        public virtual productos productos { get; set; }
    }
}
