//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturas
    {
        public string id_factura { get; set; }
        public string fk_cliente { get; set; }
        public Nullable<bool> credito { get; set; }
        public Nullable<decimal> total { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
