//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<creditos> creditos { get; set; }
        public virtual DbSet<factura_productos> factura_productos { get; set; }
        public virtual DbSet<factura_recetas> factura_recetas { get; set; }
        public virtual DbSet<facturas> facturas { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<productos_rel_recetas> productos_rel_recetas { get; set; }
        public virtual DbSet<proveedor_telefonos> proveedor_telefonos { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<recetas> recetas { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
