//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_rel_recetas
    {
        public int fk_producto { get; set; }
        public int fk_receta { get; set; }
        public decimal cantidad { get; set; }
        public int unidad { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual recetas recetas { get; set; }
    }
}
