//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_rel_recetas
    {
        public int fk_producto { get; set; }
        public int fk_receta { get; set; }
        public decimal cantidad { get; set; }
        public int unidad { get; set; }
    
        public virtual productos productos { get; set; }
        public virtual recetas recetas { get; set; }
    }
}
