//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor_telefonos
    {
        public int id_p_t { get; set; }
        public string telefono { get; set; }
        public string fk_proveedor { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
