//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor_telefonos
    {
        public int id_p_t { get; set; }
        public string telefono { get; set; }
        public string fk_proveedor { get; set; }
    
        public virtual proveedores proveedores { get; set; }
    }
}
