//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class recetas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public recetas()
        {
            this.productos_rel_recetas = new HashSet<productos_rel_recetas>();
        }
    
        public int id_receta { get; set; }
        public decimal precio { get; set; }
        public string nombre { get; set; }
        public int fk_producto_padre { get; set; }
    
        public virtual productos productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productos_rel_recetas> productos_rel_recetas { get; set; }
    }
}
